version: '3'
services:
  haproxy:
    build:
      context: ./haproxy
    ports:
      - "8088:80"
    volumes:
      - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    depends_on:
      - webber1
      - webber2
    # environment:
    #   - webber1
    #   - webber2

  webber1:
    build:
      context: ./web1
    environment:
      - CONTENEDOR="1"

  webber2:
    build:
      context: ./web1
    environment:
      - CONTENEDOR="2"
